### ISSUE TITLE
Plugin breaks Mobile UI Hamberger menu

### ISSUE THREAD

**Issue by iggbodiam** [ricardo118/grav-aviary-plugin#4]
Steps:
 - Install This plugin alongside Antimatter theme
 - Resize browser to Mobile UI size to see the hamburger menu.
 - Click the hamburger menu.
**is:** menu does not respond
 - Disable the Aviary plugin
 - Click the hamburger menu.
**is:** menu responds normally.

**should:**
 - Aviary plugin should not interfere with antimatter hamburger menu.

**Comment by ricardo118** [comment]
Fixed. I've pushed to the develop branch. I will send a full update via gpm when i fix your other issue

You can pull from develop the change right away.
