### ISSUE TITLE
can`t delete Image

### ISSUE THREAD

**Issue by fn-x** [ricardo118/grav-aviary-plugin#6]
If Aviary Image Editor is enable the delete and info button has disappeared.

![image](https://user-images.githubusercontent.com/5052352/28712246-d5681d18-738a-11e7-8727-2dbade946d25.png)

**Comment by klogachev** [comment]
Hi!
I solved the problem this way.
user/plugins/admin/themes/grav/css-compiled/template.css
add class bottom:0;
and remove class top:72px;

result:
http://prntscr.com/h888xa
http://prntscr.com/h8896p
